weights: ''
data: input/configs/military_all.yaml
hyp: input/configs/hyp.scratch.yaml
epochs: 200
batch_size: 21
resume: false
nosave: false
notest: false
name: ''
device: '0'
single_cls: true
sync_bn: false
local_rank: -1
logdir: runs/
workers: 4
use_neptune_log: true
neptune_params: input/configs/neptune_settings.json
total_batch_size: 21
world_size: 1
global_rank: -1
log_dir: runs/exp104_SIG-110
