weights: ''
data: input/configs/military_all.yaml
hyp: input/configs/hyp.scratch.yaml
epochs: 100
batch_size: 32
resume: false
nosave: false
notest: false
name: net_16_16_16_32_32_32_convs_diff_ep_100
device: '0'
single_cls: true
sync_bn: false
local_rank: -1
logdir: runs/
workers: 6
use_neptune_log: true
neptune_params: input/configs/neptune_settings.json
total_batch_size: 32
world_size: 1
global_rank: -1
log_dir: runs/exp135_net_16_16_16_32_32_32_convs_diff_ep_100_SIG-169
