weights: ''
data: input/configs/military_all.yaml
hyp: input/configs/hyp.scratch.yaml
epochs: 100
batch_size: 64
resume: false
nosave: false
notest: false
name: net_16_32_64_128_256_512_2_series_30_per_obj
device: '0'
single_cls: true
sync_bn: false
local_rank: -1
logdir: runs/
workers: 6
use_neptune_log: true
neptune_params: input/configs/neptune_settings.json
total_batch_size: 64
world_size: 1
global_rank: -1
log_dir: runs/exp156_net_16_32_64_128_256_512_2_series_30_per_obj_SIG-309
